### ISSUE TITLE
DiffusionTensorDisplayPropertiesNode does not serialize correctly

### ISSUE THREAD

**Issue by ihnorton** [SlicerDMRI/SlicerDMRI#31]
Inherits from `vtkColorTableNode`, but does not save associated `ctbl` for the ColorStorageNode, when writing MRML, leading to load errors.

```
ERROR opening colour file /tmp/foo/DiffusionTensorDisplayProperties.ctbl
ERROR opening colour file /tmp/foo/DiffusionTensorDisplayProperties_1.ctbl
ERROR opening colour file /tmp/foo/DiffusionTensorDisplayProperties_2.ctbl
Input port 0 of algorithm vtkExtractSelectedPolyDataIds(0x7f82c917cee0) has 0 connections but is not optional.
Input port 0 of algorithm vtkExtractSelectedPolyDataIds(0x7f82c917cee0) has 0 connections but is not optional.
Input port 0 of algorithm vtkExtractSelectedPolyDataIds(0x7f82c917cee0) has 0 connections but is not optional.
Input port 0 of algorithm vtkExtractSelectedPolyDataIds(0x7f82c6459990) has 0 connections but is not optional.
Input port 0 of algorithm vtkExtractSelectedPolyDataIds(0x7f82c6459990) has 0 connections but is not optional.
Input port 0 of algorithm vtkExtractSelectedPolyDataIds(0x7f82c6459990) has 0 connections but is not optional.
```

Reproduce: open FiberBundle VTK/VTP file (alone), save MRML scene, re-load MRML scene.

(Low priority since it doesn't have an adverse impact, but noting for eventual fix)

Noticed in test MRML file for #19.

**Comment by ihnorton** [comment]
Also happens in a clean scene where few FB nodes were imported directly:
```
ERROR opening colour file /Users/inorton/work/test_fb/atlasconnectome/NEWclustering_k1200_30000fiber/iteration_00009/initial_clusters/DiffusionTensorDisplayProperties_1197.ctbl
```

**Comment by ljod** [comment]
Is there some way we can avoid needing to save these color tables? Having so many of them would be extremely annoying for all users especially me.

**Comment by ayarmarkovich** [comment]
It looks like the extra storage node are created on saving of the SceneView node. It does this to prevent some other issues related to restoring Scene Views. I would need to dig deeper to figure out how to fix this without breaking other functionality. It may take couple more days, do you want me to spend this time? Also, I would suggest to keep track of slicer issues in the Mantis so we can reference other issues there.

**Comment by ayarmarkovich** [comment]
Hi Lauren, do you remember why you made a subclass of vtkMRMLColorTableNode? Does it need to be that? If we change this it will not try to save it into a file. I tacked the original problem to changes made by Nicole in vtkMRMLSceneViewNode in rev 24377, I am discussing the issue with her, but it i related to other bugs, and the easiest way to fix would be not dervie vtkMRMLDiffusionTensorDisplayPropertiesNode from  vtkMRMLColorTableNode

**Comment by ljod** [comment]
Isaiah do you know why? Is there dti specific stuff in it?

Lauren



On Fri, May 13, 2016 at 8:20 AM -0700, "ayarmarkovich" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lauren, do you remember why you made a subclass of vtkMRMLColorTableNode? Does it need to be that? If we change this it will not try to save it into a file. I tacked the original problem to changes made by Nicole in vtkMRMLSceneViewNode in rev 24377, I am discussing the issue with her, but it i related to other bugs, and the easiest way to fix would be not dervie vtkMRMLDiffusionTensorDisplayPropertiesNode from vtkMRMLColorTableNode

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/SlicerDMRI/SlicerDMRI/issues/31#issuecomment-219074702>


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by ihnorton** [comment]
There is a comment about why at the beginning of the header (`vtkMRMLDiffusionTensorDisplayPropertiesNode.h`):
```
 32 /// This class inherits from the vtkMRMLColorNode->vtkMRMLColorTableNode superclasses,
 33 /// used for vtkMRMLModelNodes and vtkMRMLVolumeNodes, in order to
 34 /// provide specific lookup tables for the scalar invariant display.
```

However, such functionality was not implemented as far as I can tell:
```
493   /// TO DO: add specific lookup tables ranging from 0..1 for or -1 1
494   /// for scalar invariants with those ranges
```

So I think changing the parent is fine.

On the other hand, the easiest fix to override `vtkMRMLColorTableNode::CreateDefaultStorageNode` to return `NULL`, which will prevent a storage node generation at all. Old scenes with the `ColorStorageNode` items inside them would still print the errors but I don't know if that can be avoided in any case.

**Comment by ayarmarkovich** [comment]
Submitted a slicer bug:
http://na-mic.org/Bug/view.php?id=4190

**Comment by ayarmarkovich** [comment]
Fixed using Isaiah's suggestion: Set default storage node for vtkMRMLDiffusionTensorDisplayPropertiesNode to NULL since it does not need to store any data in a separate file.
At revision: 25067
