### ISSUE TITLE
FiberBundleLabelSelect not showing in menu Diffusion.Tractography.Region-based

### ISSUE THREAD

**Issue by iZsh** [SlicerDMRI/SlicerDMRI#92]
Hello,

I'm running Slicer 4.8 with Mac OS X 10.13.1
I don't see the tool FiberBundleLabelSelect in the menu Diffusion.Tractography.Region-based

I do see the code and the xml in Slicer.app/Contents/Extensions-26489/SlicerDMRI/lib/Slicer-4.8/cli-modules

but for some reasons it's not showing in the menu

**Comment by ihnorton** [comment]
Hi @iZsh, I just tried on Mac as well, and the module should be available in 4.8 under the following menu (screenshot below). If not, please let us know!

Also, if you read some documentation with the old name, please post a link here and we will make sure to update the documentation. Thanks!

![image](https://user-images.githubusercontent.com/327706/33330241-5731169a-d42c-11e7-9486-fe914f0e0afb.png)

**Comment by iZsh** [comment]
I found my issue. I think Slicer gets confused whenever you upgrade it about what is really installed and what is not (since on mac os X, plugins are installed within slicer's ".app directory").

Uninstalling all the diffusions plugins I had and reinstalling them, including slicer dmri, fixed the issue.

**Comment by ihnorton** [comment]
The module display name was updated well before 4.8, so I'm puzzled how that would have happened -- extensions should be independently installed within the unique .app directory for a specific Slicer version. The one case I can think of is if you built Slicer locally but installed extensions from the extension manager (this is sort of discouraged, because it doesn't work on some platforms -- ahem, *Windows* -- but I believe it does work on Mac provided that an extension build-set exists matching your local Slicer commit).

Anyway, glad it works now.
